<?php

/**
 * @file
 * Module contained miscelanious helper functions and hooks.
 */


/**
 * Implements hook_menu().
 */
function vb_misc_menu() {
 
  
  $items['test'] = array(
    'title' => 'Test page',
    'page callback' => 'vb_misc_testPage',
    //'access arguments' => array('administer content'),
    'access arguments' => array('administer taxonomy'), 
    'type' => MENU_CALLBACK,
  );
  
  
  return $items;
}


/**
 * Test page function for url /test.
 */
function vb_misc_testPage() {
  
  $out = '<div>Start test...</div>';

  
  vb_misc_import_remote_blogPosts();
  
  /*
  $query = db_select('voip_comments', 'c')
    ->fields('c')
    ->condition('c.comment_approved', 1)
    ->condition('c.comment_approved', 'spam', '!=');
  $wp_comments = $query->execute();
  */
  

  
  return $out . '<br>End of Test';
}



/**
 * Imports blog_posts from a remote table.
 */
function vb_misc_import_remote_blogPosts() { 
  
  
  $remote_category = array(
    5356 =>	'Best of',
    343	=> 'Calling plans',
    345	=> 'Companies',
    353	=> 'Conferences',
    728	=> 'Dangers',
    349	=> 'Development Tools',
    6136 => 'Did you know',
    370	=> 'General',
    1060 => 'Hardware',
    729	=> 'Industry News',
    5638 => 'Information About',
    351	=> 'Interviews',
    344	=> 'IP Business Phone',
    1969 => 'Misc',
    358	=> 'New Application',
    1058 => 'Podcasts',
    1771 => 'privacy',
    6134 => 'Quick introduction',
    1672 => 'skype',
    426	=> 'Terminal',
    807202 => 'Uncategorized',
  );

  $category_map = array(
    5356 =>	1,
    343	=> 2,
    345	=> 3,
    353	=> 4,
    728	=> 5,
    349	=> 6,
    6136 => 7,
    370	=> 8,
    1060 => 9,
    729	=> 10,
    5638 => 11,
    351	=> 12,
    344	=> 13,
    1969 => 14,
    358	=> 15,
    1058 => 16,
    1771 => 17,
    1672 => 18,
    426	=> 19,
    6134 => 20,
  );
  
  
  $query = db_select('mt_entry_EXPORT', 'vp')
        ->fields('vp');
  $query->leftJoin('mt_placement_EXPORT', 'pl', 'pl.placement_entry_id = vp.entry_id AND pl.placement_is_primary = 1');
  $query->fields('pl', array('placement_category_id'));
  
  //$query->range(0, 20);
  $results = $query->execute()->fetchAll();
  
  dpm($results);
  
 //return;
 
 
  foreach ($results as $result) {
    
    $form_state['values'] = array(
      'title' => $result->entry_title,
      'post_date' => $result->entry_created_on,
      'created' => strtotime($result->entry_created_on),
      'changed' => strtotime($result->entry_created_on),
      'category' => $category_map[$result->placement_category_id],
      'url_alias' => str_replace('http://www.voip-weblog.com/', '', $result->url),
      'ID' => $result->entry_id,
    );
    
    $form_state['values']['body']['und'][0]['value'] = str_replace('--', '-', $result->entry_text);
    
    if (preg_match('/(.*)<!--more-->(.*)/s', $form_state['values']['body']['und'][0]['value'], $matches)) {
      //dpm($matches);
      ////$form_state['values']['body']['und'][0]['value'] = $matches[1] . /*'<span id="more"></span>' .*/ $matches[2];
      ////////$form_state['values']['body']['und'][0]['summary'] = $matches[1] . '<p><a href="/' . $form_state['values']['url_alias'] . '#more" class="more-link">Read the rest of this entry »</a></p>';
      $form_state['values']['body']['und'][0]['summary'] = $matches[1];
      //$body_full_markup = preg_replace('|\[video:.*(http.*)\]|', '<a href="$1"> [Watch a video] </a>', $body_full_markup);
    }
    else {
      $form_state['values']['body']['und'][0]['summary'] = '';
    }
    
    
    // Add only one node.
    vb_misc_createNode_BlogPost($form_state);
    //break;
  }
}


/**
 * Creates a node blog_post.
 */
function vb_misc_createNode_BlogPost($form_state) { 
  
  global $user;
  
  $node = new stdClass();
  $node->type = 'blog_post';
  node_object_prepare($node);
  
  $node->date = $form_state['values']['post_date'];
  $node->created = $form_state['values']['created'];
  $node->changed = $form_state['values']['changed'];
  
          
  $node->title = $form_state['values']['title'];
  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->status = 1;
  $node->promote = 0;
  $node->sticky = 0;
  $node->comment = 0;
  
  $node->body[$node->language][0]['format'] = 'full_html';
  $node->body[$node->language][0]['value'] = $form_state['values']['body']['und'][0]['value'];
  $node->body[$node->language][0]['summary'] = $form_state['values']['body']['und'][0]['summary'];
  $node->body[$node->language][0]['safe_summary'] = check_plain($form_state['values']['body']['und'][0]['summary']);
  $node->body[$node->language][0]['safe_value'] = check_plain($form_state['values']['body']['und'][0]['value']);
  
  $node->field_extra_data[$node->language][0] = array(
    'value' => NULL,
    'safe_value' => NULL,
    'format' => 'full_html',
  );
  $node->field_main_image[$node->language][0] = array(
    'value' => NULL,
    'safe_value' => NULL,
    'format' => 'full_html',
  );
  $node->field_a_teaser[$node->language][0] = array(
    'value' => NULL,
    'safe_value' => NULL,
    'format' => 'full_html',
  );
  
  $node->field_old_id[$node->language][0]['value'] = $form_state['values']['ID'];
  
  if ($form_state['values']['category']) {
    $node->field_categories[$node->language][0]['tid'] = $form_state['values']['category'];
  }
  
  
  $node->path = array(
    'alias' => $form_state['values']['url_alias'],
    'language' => $node->language,
    'pathauto' => 0,
  );
  
  //dpm($node);
  //return;
  
  if ($node = node_submit($node)) {
    node_save($node);
    drupal_set_message('Saved, Ok!', 'warning');
  }
  
}


